### ISSUE TITLE
Fatal Python Error plugin_manager(0.0.13) and pymodaq (3.1.12)

### ISSUE THREAD

**Issue by jerlfan** [CEMES-CNRS/pymodaq_plugin_manager#5]
Hi,

I have installed the latest version of pymodaq (3.1.12) on my computer (Windows 8).
It works fine but i have encoutered several issues.

In particular I am not able to install plugins!
 --> using plugin_manager I have the following problem:

"Fatal Python erro: init!sys!streams: can't initialize sys standard streams
ValueError: Cannot open console output buffer for reading"

I am trying to resolve this problem but I am not yet succesful. If you have suggestions...

Below the (windows 8) details of the issue:

Signature du problème :
Nom d’événement de problème: BEX64
Nom de l’application: python.exe
Version de l’application: 3.7.10150.1013
Horodatage de l’application: 60394710
Nom du module par défaut: ucrtbase.DLL
Version du module par défaut: 10.0.17134.12
Horodateur du module par défaut: 587decd7
Décalage de l’exception: 000000000006e75e
Code de l’exception: c0000409
Données d’exception: 0000000000000007
Version du système: 6.3.9600.2.0.0.256.48
Identificateur de paramètres régionaux: 1036
Information supplémentaire n° 1: 45b0
Information supplémentaire n° 2: 45b089d322579fb6ea427640784cdbad
Information supplémentaire n° 3: 5d37
Information supplémentaire n° 4: 5d3767b2124964653156aab613d58c39

**Comment by seb5g** [comment]
there are some known issues with capturing the standard output from the console on some versions of windows. I just pushed a commit on the plugin_manager repo https://github.com/CEMES-CNRS/pymodaq_plugin_manager/commit/ca205dcdf8e15c93f35aa82a077412fd169f2d04 to take this into account. Could you install this commit and try again. The only drwback is that you'll not have any info displayed on the UI but only in the console

**Comment by jerlfan** [comment]
I update plugin_manager from the github repository. I still have the same problem. See below.
![Capture d’écran 2021-05-10 à 14 10 38](https://user-images.githubusercontent.com/6199478/117657321-b897c980-b199-11eb-8536-53780fc575e2.png)

**Comment by seb5g** [comment]
Could you try out of pymodaq this lines of codes:
`import sys`
`import subprocess`
`command = [sys.executable, '-m', 'pip', 'list']`
`subprocess.Popen(command)`

and check if it crashes

**Comment by seb5g** [comment]
then could you run the module that generates the error in debug mode in pycharm or other IDE and track where the issue is generated?

**Comment by seb5g** [comment]
for pyqt5 5.9.2 there may be some more recent functionnalities I'm using but overall it should be fine

**Comment by jerlfan** [comment]
I run manager.py in anaconda3/envs/pymodaq/Lib/site-packages/pymodaq_plugin_manager in pycharm. Everything works perfectly fine and I am able to install and uninstall all packages.

When I run plugin_manager command in anaconda powershell I got the same error as previsouly. 

I installed the last version of pyqt5 to be sure (renaming the QT5Bluetooth.dll)

**Comment by seb5g** [comment]
Found the origin of the problem when using the console directly. Seems you cannot fetch info from the console from input and errors but only from out... I'm not very fluent in this, but the goal was to get info from the console to print on the user interface of the module. It still does but with no error when using the console directly. @jerlfan could you try this again (on source or release 0.014) and close the issue if fine?

**Comment by jerlfan** [comment]
Everything works fine with release 0.0.14!
